// examples/pinia/pages/index/Counter.vue
<script setup>
import { useCounterStore } from '../../renderer/stores/counter'
const counterStore = useCounterStore();  
</script>

<template>
  <div>
    <h1>Counter page</h1>
		<h2>Count is: {{ counterStore.countValue }}</h2>
		<button @click.prevent="counterStore.increment()" class="btn" type="button">Increment</button>
		<button @click.prevent="counterStore.decrement()" class="btn" type="button">Decrement</button>
  </div>
</template>

// examples/i18n/components/Counter.jsx
export { Counter }

import React, { useState } from 'react'
import { LocaleText } from '../renderer/LocaleText'

function Counter() {
  const [count, setCount] = useState(0)
  return (
    <button type="button" onClick={() => setCount((count) => count + 1)}>
      <LocaleText>Counter</LocaleText> {count}
    </button>
  )
}
