// boilerplates/boilerplate-vue-ts/pages/star-wars/@id/+Page.vue
<template>
  <h1>{{ data.movie.title }}</h1>
  Release Date: {{ data.movie.release_date }}
  <br />
  Director: {{ data.movie.director }}
  <br />
  Producer: {{ data.movie.producer }}
</template>

<script lang="ts" setup>
import type { Data } from './+data'
import { useData } from '../../../renderer/useData'
const data = useData<Data>()
</script>

// boilerplates/boilerplate-react/pages/star-wars/@id/+Page.jsx
export { Page }

import { useData } from '../../../renderer/useData'

function Page() {
  const { movie } = useData()
  return (
    <>
      <h1>{movie.title}</h1>
      Release Date: {movie.release_date}
      <br />
      Director: {movie.director}
      <br />
      Producer: {movie.producer}
    </>
  )
}
