// test-deprecated-design/react-streaming/renderer/Layout.jsx
import React from 'react'
import './Layout.css'

export { Layout }

function Layout({ children }) {
  return (
    <React.StrictMode>
      <Frame>
        <Sidebar>
          <a className="navitem" href="/">
            Home
          </a>
          <a className="navitem" href="/about">
            About
          </a>
        </Sidebar>
        <Content>{children}</Content>
      </Frame>
    </React.StrictMode>
  )
}

function Frame({ children }) {
  return (
    <div
      style={{
        display: 'flex',
        maxWidth: 900,
        margin: 'auto'
      }}
    >
      {children}
    </div>
  )
}

function Sidebar({ children }) {
  return (
    <div
      style={{
        padding: 20,
        paddingTop: 42,
        flexShrink: 0,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        lineHeight: '1.8em'
      }}
    >
      {children}
    </div>
  )
}

function Content({ children }) {
  return (
    <div
      style={{
        padding: 20,
        paddingBottom: 50,
        borderLeft: '2px solid #eee',
        minHeight: '100vh'
      }}
    >
      {children}
    </div>
  )
}

// examples/svelte-v1/renderer/Layout.svelte
<script>
  export let Page;
  export let pageProps;
</script>

<div class="layout">
  <nav class="sidebar">
    <a class="nav-item" href="/">
      Home
    </a>
    <a class="nav-item" href="/about">
      About
    </a>
  </nav>

  <div class="content">
    <svelte:component this={Page} {...pageProps} />
  </div>
</div>

<style>
  :global(body) {
    font-family: sans-serif;
    margin: 0;
  }

  :global(*),
  :global(*::before)
  :global(*::after) {
    box-sizing: border-box;
  }

  :global(a) {
    text-decoration: none;
  }

  .layout {
    display: flex;
    margin: auto;
    max-width: 900px;
  }

  .sidebar {
    align-items: center;
    display: flex;
    flex-direction: column;
    flex-shrink: 0;
    line-height: 1.8em;
    padding: 42px 20px 20px 20px;
  }

  .nav-item {
    padding: 3px;
  }

  .content {
    border-left: 2px solid #eee;
    min-height: 100vh;
    padding: 20px 20px 50px 20px;
  }
</style>
