// examples/solid/renderer/_default.page.client.tsx
import { hydrate, render } from "solid-js/web";
import { useClientRouter } from "vite-plugin-ssr/client/router";
import { PageLayout } from "./PageLayout";

let dispose: () => void;

const { hydrationPromise } = useClientRouter({
  render(pageContext) {
    const content = document.getElementById("page-view");
    const { Page, pageProps } = pageContext;

    // Dispose to prevent duplicate pages when navigating.
    if (dispose) dispose();

    // Render the page
    if (pageContext.isHydration) {
      // This is the first page rendering; the page has been rendered to HTML
      // and we now make it interactive.
      dispose = hydrate(
        () => (
          <PageLayout>
            <Page {...pageProps} />
          </PageLayout>
        ),
        content!
      );
    } else {
      // Render new page
      render(
        () => (
          <PageLayout>
            <Page {...pageProps} />
          </PageLayout>
        ),
        content!
      );
    }
  },
  onTransitionStart,
  onTransitionEnd,
});

hydrationPromise.then((s) => {
  console.log("Hydration finished; page is now interactive.");
});

function onTransitionStart() {
  console.log("Page transition start");
}
function onTransitionEnd() {
  console.log("Page transition end");
}

// examples/preact-client-routing/renderer/_default.page.client.tsx
// @ts-nocheck 
import { hydrate, render } from 'preact'
import { getPage } from 'vite-plugin-ssr/client'
import { useClientRouter } from 'vite-plugin-ssr/client/router'
import { PageShell } from './PageShell'
import type { PageContext } from './types'
import type { PageContextBuiltInClient } from 'vite-plugin-ssr/client'

const { hydrationPromise } = useClientRouter({
  render(pageContext: PageContextBuiltInClient & PageContext) {
    const { Page, pageProps } = pageContext
    const page = (
      <PageShell pageContext={pageContext}>
        <Page {...pageProps} />
      </PageShell>
    )
    const container = document.querySelector('body')
    console.log({ container, Page, pageProps })
    if (pageContext.isHydration && container) {
      hydrate(page, container)
    } else if (container) {
      render(page, container)
    }
    document.title = getPageTitle(pageContext)
  },
  onTransitionStart,
  onTransitionEnd,
})

hydrationPromise.then(() => {
  console.log('Hydration finished; page is now interactive.')
})

function onTransitionStart() {
  console.log('Page transition start')
  document.querySelector('#page-content')!.classList.add('page-transition')
}
function onTransitionEnd() {
  console.log('Page transition end')
  document.querySelector('#page-content')!.classList.remove('page-transition')
}

function getPageTitle(pageContext: {
  pageExports: { documentProps?: { title?: string } }
  documentProps?: { title?: string }
}): string {
  const title =
    // For static titles (defined in the `export { documentProps }` of the page's `.page.js`)
    (pageContext.pageExports.documentProps || {}).title ||
    // For dynamic tiles (defined in the `export addContextProps()` of the page's `.page.server.js`)
    (pageContext.documentProps || {}).title ||
    'Demo'
  return title
}
