// boilerplates/boilerplate-vue/renderer/Link.vue
<template>
  <a :class="{ active: isActive }">
    <slot />
  </a>
</template>
<style scoped>
a {
  padding: 2px 10px;
  margin-left: -10px;
}
a.active {
  background-color: #eee;
}
</style>
<script setup>
import { useAttrs, computed } from 'vue'
import { usePageContext } from './usePageContext'

const pageContext = usePageContext()
const { href } = useAttrs()
const isActive = computed(() => {
  const { urlPathname } = pageContext
  return href === '/' ? urlPathname === href : urlPathname.startsWith(href)
})
</script>

// examples/stem-react/pages/_default/Link.tsx
export { Link }

import { usePageContext } from '@brillout/stem-react'
import React from 'react'

function Link({ href, children }: { href: string; children: string }) {
  const pageContext = usePageContext() as { urlPathname: string } // TODO
  const { urlPathname } = pageContext
  const isActive = href === '/' ? urlPathname === href : urlPathname.startsWith(href)
  return (
    <a href={href} className={isActive ? 'is-active' : undefined}>
      {children}
    </a>
  )
}
