// boilerplates/boilerplate-vue-ts/pages/_error/+Page.vue
<template>
  <div v-if="is404">
    <h1>404 Page Not Found</h1>
    <p>This page could not be found.</p>
  </div>
  <div v-else>
    <h1>500 Internal Error</h1>
    <p>Something went wrong.</p>
  </div>
</template>

<script lang="ts" setup>
import { usePageContext } from '../../renderer/usePageContext'
const pageContext = usePageContext()
const { is404 } = pageContext
defineProps(['is404'])
</script>

// boilerplates/boilerplate-react/pages/_error/+Page.jsx
export { Page }

import { usePageContext } from '../../renderer/usePageContext'

function Page() {
  const pageContext = usePageContext()
  if (pageContext.is404) {
    return (
      <>
        <h1>404 Page Not Found</h1>
        <p>This page could not be found.</p>
      </>
    )
  } else {
    return (
      <>
        <h1>500 Internal Error</h1>
        <p>Something went wrong.</p>
      </>
    )
  }
}
