// packages/create-vike-core/boilerplate-react/renderer/Link.jsx
import PropTypes from 'prop-types'
import { usePageContext } from './usePageContext'

export { Link }

Link.propTypes = {
  className: PropTypes.string,
  href: PropTypes.string.isRequired,
}
function Link(props) {
  const pageContext = usePageContext()
  const { urlPathname } = pageContext
  const { href } = props
  const isActive = href === '/' ? urlPathname === href : urlPathname.startsWith(href)
  const className = [props.className, isActive && 'is-active'].filter(Boolean).join(' ')
  return <a {...props} className={className} />
}

// boilerplates/boilerplate-vue/renderer/Link.vue
<template>
  <a :class="{ active: isActive }">
    <slot />
  </a>
</template>
<style scoped>
a {
  padding: 2px 10px;
  margin-left: -10px;
}
a.active {
  background-color: #eee;
}
</style>
<script setup>
import { useAttrs, computed } from 'vue'
import { usePageContext } from './usePageContext'

const pageContext = usePageContext()
const { href } = useAttrs()
const isActive = computed(() => {
  const { urlPathname } = pageContext
  return href === '/' ? urlPathname === href : urlPathname.startsWith(href)
})
</script>
