// examples/react-full-v1/renderer/+onRenderClient.tsx
// https://vite-plugin-ssr.com/onRenderClient
export default onRenderClient

import './css/index.css'
import React from 'react'
import ReactDOM from 'react-dom/client'
import { PageShell } from './PageShell'
import { getPageTitle } from './getPageTitle'
import type { PageContextClient } from 'vite-plugin-ssr/types'

let root: ReactDOM.Root
async function onRenderClient(pageContext: PageContextClient) {
  const { Page, pageProps } = pageContext
  const page = (
    <PageShell pageContext={pageContext}>
      <Page {...pageProps} />
    </PageShell>
  )
  const container = document.getElementById('page-view')!
  if (pageContext.isHydration) {
    root = ReactDOM.hydrateRoot(container, page)
  } else {
    if (!root) {
      root = ReactDOM.createRoot(container)
    }
    root.render(page)
  }
  document.title = getPageTitle(pageContext)
}

// examples/solid-spa-v1/renderer/+onRenderClient.tsx
// https://vite-plugin-ssr.com/onRenderClient
export default onRenderClient

import { render } from 'solid-js/web'
import type { PageContextClient } from './types'

/**
 * A function that disposes previously rendered pages.
 *
 * If the function is not executed, each route change will
 * append a page to the DOM without clearing (disposing)
 * the previous one.
 */
let disposePreviousPage: () => void

async function onRenderClient(pageContext: PageContextClient) {
  const { Page } = pageContext

  if (disposePreviousPage) {
    disposePreviousPage()
  }

  // render the page and save the dispose function of that page
  disposePreviousPage = render(() => <Page />, document.getElementById('root'))
}
