// examples/react-data-fetching/pages/star-wars/index/+Page.tsx
export default Page

import React from 'react'
import { useData } from '../../../renderer/useData'

function Page() {
  const data = useData()
  const movies = data?.movies || []
  return (
    <>
      <h1>Star Wars Movies</h1>
      <ol>
        {movies.map(({ id, title, release_date }) => (
          <li key={id}>
            <a href={`/star-wars/${id}`}>{title}</a> ({release_date})
          </li>
        ))}
      </ol>
      <p>
        Source: <a href="https://star-wars.brillout.com">star-wars.brillout.com</a>.
      </p>
      <p>
        Data can be fetched by using the <code>data()</code> hook.
      </p>
    </>
  )
}

// examples/vue-full/pages/star-wars/index/+Page.vue
<template>
  <h1>Star Wars Movies</h1>
  <ol>
    <li v-for="item in data.movies" :key="item.id">
      <a :href="'/star-wars/' + item.id">{{ item.title }}</a> ({{ item.release_date }})
    </li>
  </ol>
  <p>Source: <a href="https://star-wars.brillout.com">star-wars.brillout.com</a>.</p>
  <p>Data can be fetched by using the <code>data()</code> hook.</p>
</template>

<script lang="ts" setup>
import type { Data } from './+data'
import { useData } from '../../../renderer/useData'
const data = useData<Data>()
</script>
