// examples/react-full/pages/_default/types.ts
import type { PageContextBuiltIn } from "vite-plugin-ssr/types";
export type Component = (pageProps: any) => JSX.Element;
export type Children = React.ReactNode | React.ReactNode[];
export type PageContext = PageContextBuiltIn & {
  Page: Component;
  pageExports: {
    documentProps?: {
      title: string;
    };
  };
  pageProps: Record<string, unknown>;
  documentProps?: {
    title: string;
  };
};

// examples/solid-ssr/renderer/types.ts
import { Component } from 'solid-js'
import type { PageContextBuiltIn } from 'vite-plugin-ssr/types'
export type PageProps = {}
type Page = Component<PageProps>
export type PageContext = PageContextBuiltIn<Page> & {
  pageProps: PageProps
  documentProps?: {
    title?: string
    description?: string
  }
}
