// examples/solid/pages/index/index.page.tsx
import { Component } from "solid-js";
import { Counter } from "./Counter";

const Page: Component = () => {
  return (
    <>
      <h1>Welcome</h1>
      This page is:
      <ul>
        <li>Rendered to HTML.</li>
        <li>
          Interactive. <Counter />
        </li>
      </ul>
    </>
  );
}

export { Page };

// test-deprecated-design/cloudflare-workers-react-full/pages/index.page.tsx
export { Page }

import React from 'react'
import { Counter } from '../components/Counter'

function Page() {
  return (
    <>
      <h1>Welcome</h1>
      This page is:
      <ul>
        <li>Rendered to HTML.</li>
        <li>
          Interactive. <Counter />
        </li>
      </ul>
    </>
  )
}
