// examples/cloudflare-workers/renderer/_error.page.jsx
import React from "react";

export { Page };

function Page({ is404 }) {
  if (is404) {
    return (
      <>
        <h1>404 Page Not Found</h1>
        This page could not be found.
      </>
    );
  } else {
    return (
      <>
        <h1>500 Internal Server Error</h1>
        Something went wrong.
      </>
    );
  }
}

// boilerplates/boilerplate-vue-ts/renderer/_error.page.vue
<template>
  <div v-if="is404">
    <h1>404 Page Not Found</h1>
    <p>This page could not be found.</p>
  </div>
  <div v-else>
    <h1>500 Internal Server Error</h1>
    <p>Something went wrong.</p>
  </div>
</template>

<script lang="ts">
const props = ['is404']
export default { props }
</script>
