// examples/renderer/renderer/components/Link.tsx
import React from 'react'
import { usePageContext } from '../hooks/usePageContext'

export { Link }

function Link(props: any) {
  const pageContext = usePageContext() as any
  const className = [props.className, pageContext.urlPathname === props.href && 'is-active'].filter(Boolean).join(' ')
  return <a {...props} className={className} />
}

// boilerplates/boilerplate-vue-ts/renderer/Link.vue
<template>
  <a :class="{ active: pageContext.urlPathname === $attrs.href }">
    <slot />
  </a>
</template>
<style scoped>
a {
  padding: 3px 10px;
}
a.active {
  background-color: #eee;
}
</style>
<script lang="ts" setup>
import { usePageContext } from './usePageContext'
const pageContext = usePageContext()
</script>
