// examples/react-full/renderer/usePageContext.tsx
import React, { useContext } from "react";
import type { PageContext } from "./types";

export { PageContextProvider };
export { usePageContext };

const Context = React.createContext<PageContext>(undefined as any);

function PageContextProvider({
  pageContext,
  children,
}: {
  pageContext: PageContext;
  children: React.ReactNode;
}) {
  return <Context.Provider value={pageContext}>{children}</Context.Provider>;
}

function usePageContext() {
  const pageContext = useContext(Context);
  return pageContext;
}

// examples/solid-ssr-v1/composables/usePageContext.ts
import { createContext, useContext } from 'solid-js'

import { IPageContext } from '#/types'

export const PageContext = createContext<IPageContext>()

/** Access the pageContext from any SolidJS component */
export function usePageContext() {
  const pageContext = useContext(PageContext)
  if (!pageContext) throw new Error('<PageContextProvider> is needed for being able to use usePageContext()')
  return pageContext
}
