// examples/vue-full-v1/pages/index/+Page.vue
<template>
  <h1>Welcome to <code>vite-plugin-ssr</code></h1>
  This page is:
  <ul>
    <li>Rendered to HTML.</li>
    <li>Interactive. <Counter /></li>
  </ul>
  <p>
    <button @click="randomNavigation">Random Page</button>
  </p>
</template>

<script lang="ts" setup>
import Counter from '../../components/Counter.vue'
import { navigate } from 'vite-plugin-ssr/client/router'

const randomNavigation = () => {
  const randomIndex = Math.floor(Math.random() * 3)
  navigate(['/markdown', '/star-wars', '/hello/alice'][randomIndex])
}
</script>

// examples/react-full-v1-single-page-file/pages/index/Page.tsx
export default Page

import React from 'react'
import { navigate } from 'vite-plugin-ssr/client/router'
import { Counter } from '../../components/Counter'

function Page() {
  return (
    <>
      <h1>
        Welcome to <code>vite-plugin-ssr</code>
      </h1>
      This page is:
      <ul>
        <li>Rendered to HTML.</li>
        <li>
          Interactive. <Counter />
        </li>
      </ul>
      <p>
        We <code>export const clientRouting = true</code> to enable Client Routing.{' '}
        <button
          onClick={() => {
            const randomIndex = Math.floor(Math.random() * 3)
            navigate(['/markdown', '/star-wars', '/hello/alice'][randomIndex])
          }}
        >
          Random Page
        </button>
      </p>
    </>
  )
}
