// examples/layouts-vue/renderer/LayoutDefault.vue
<template>
  <div class="layout">
    <div class="navigation">
      <a class="navitem" href="/">Home</a>
      <a class="navitem" href="/about">About</a>
      <a class="navitem" href="/starship">Starship</a>
    </div>
    <div class="content"><slot /></div>
  </div>
</template>

<style scoped>
.layout {
  display: flex;
  max-width: 900px;
  margin: auto;
}
.content {
  padding: 20px;
  border-left: 2px solid #eee;
  padding-bottom: 50px;
  min-height: 100vh;
}
.navigation {
  padding: 20px;
  padding-top: 42px;
  flex-shrink: 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  line-height: 1.8em;
}
.navitem {
  padding: 3px;
}
</style>

// examples/layouts-react/renderer/LayoutDefault.jsx
export { LayoutDefault }

import './LayoutDefault.css'

function LayoutDefault({ children }) {
  return (
    <div
      style={{
        display: 'flex',
        maxWidth: 900,
        margin: 'auto',
      }}
    >
      <Sidebar>
        <a className="navitem" href="/">
          Home
        </a>
        <a className="navitem" href="/about">
          About
        </a>
        <a className="navitem" href="/starship">
          Starship
        </a>
      </Sidebar>
      <Content>{children}</Content>
    </div>
  )
}

function Sidebar({ children }) {
  return (
    <div
      style={{
        padding: 20,
        paddingTop: 42,
        flexShrink: 0,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        lineHeight: '1.8em',
      }}
    >
      {children}
    </div>
  )
}

function Content({ children }) {
  return (
    <div
      style={{
        padding: 20,
        paddingBottom: 50,
        borderLeft: '2px solid #eee',
        minHeight: '100vh',
      }}
    >
      {children}
    </div>
  )
}
