// examples/svelte-v1/renderer/Layout.svelte
<script>
  export let Page;
  export let pageProps;
</script>

<div class="layout">
  <nav class="sidebar">
    <a class="nav-item" href="/">
      Home
    </a>
    <a class="nav-item" href="/about">
      About
    </a>
  </nav>

  <div class="content">
    <svelte:component this={Page} {...pageProps} />
  </div>
</div>

<style>
  :global(body) {
    font-family: sans-serif;
    margin: 0;
  }

  :global(*),
  :global(*::before)
  :global(*::after) {
    box-sizing: border-box;
  }

  :global(a) {
    text-decoration: none;
  }

  .layout {
    display: flex;
    margin: auto;
    max-width: 900px;
  }

  .sidebar {
    align-items: center;
    display: flex;
    flex-direction: column;
    flex-shrink: 0;
    line-height: 1.8em;
    padding: 42px 20px 20px 20px;
  }

  .nav-item {
    padding: 3px;
  }

  .content {
    border-left: 2px solid #eee;
    min-height: 100vh;
    padding: 20px 20px 50px 20px;
  }
</style>

// packages/create-vike-core/boilerplate-vue-ts/renderer/Layout.vue
<template>
  <div id="page-container">
    <div id="sidebar">
      <a href="/" id="logo-container">
        <img src="./logo.svg" height="64" width="64" alt="logo" />
      </a>
      <Link href="/">Welcome</Link>
      <Link href="/about">About</Link>
      <Link href="/star-wars">Data Fetching</Link>
    </div>
    <div id="page-content"><slot /></div>
  </div>
</template>

<script lang="ts" setup>
import Link from './Link.vue'
import './css/index.css'
</script>

<style>
#sidebar a {
  padding: 2px 10px;
  margin-left: -10px;
}
#sidebar a.is-active {
  background-color: #eee;
}
</style>

<style scoped>
#page-container {
  display: flex;
  max-width: 900px;
  margin: auto;
}
#page-content {
  padding: 20px;
  padding-bottom: 50px;
  min-height: 100vh;
}
#sidebar {
  padding: 20px;
  flex-shrink: 0;
  display: flex;
  flex-direction: column;
  line-height: 1.8em;
  border-right: 2px solid #eee;
}
#logo-container {
  margin-top: 20px;
  margin-bottom: 10px;
}
</style>
