// examples/vike-react-min/pages/index/Page.tsx
export default Page

import React from 'react'
import { Counter } from './Counter.js'

function Page() {
  return (
    <>
      <h1>Vike React app</h1>
      This page is:
      <ul>
        <li>Rendered to HTML.</li>
        <li>
          Interactive. <Counter />
        </li>
      </ul>
    </>
  )
}

// examples/solid-ssr-v1/pages/index/+Page.tsx
import { Component } from 'solid-js'
import { Counter } from './Counter'

const Page: Component = () => {
  return (
    <>
      <h1>Welcome</h1>
      <div>
        This page is:
        <ul>
          <li>Rendered to HTML.</li>
          <li>
            Interactive. <Counter />
          </li>
        </ul>
      </div>
    </>
  )
}

export default Page
