// examples/solid-ssr-v1/renderer/usePageContext.tsx
export { usePageContext }
export { PageContextProvider }

import { useContext, createContext, type JSX } from 'solid-js'
import { type Store } from 'solid-js/store'
import type { PageContext } from 'vike/types'

const Context = createContext<Store<PageContext>>()

function PageContextProvider(props: { pageContext: Store<PageContext>; children: JSX.Element }) {
  if (!props.pageContext) throw new Error('Argument pageContext missing')
  return <Context.Provider value={props.pageContext}>{props.children}</Context.Provider>
}

/** Access the pageContext from any SolidJS component */
function usePageContext() {
  const pageContext = useContext(Context)
  if (!pageContext) throw new Error('<PageContextProvider> is needed for being able to use usePageContext()')
  return pageContext
}

// test-deprecated-design/react-full/renderer/usePageContext.tsx
import React, { useContext } from 'react'
import type { PageContext } from 'vike/types'

export { PageContextProvider }
export { usePageContext }

const Context = React.createContext<PageContext>(undefined as any)

function PageContextProvider({ pageContext, children }: { pageContext: PageContext; children: React.ReactNode }) {
  return <Context.Provider value={pageContext}>{children}</Context.Provider>
}

function usePageContext() {
  const pageContext = useContext(Context)
  return pageContext
}
