// examples/solid-ssr/renderer/_default.page.client.tsx
export const clientRouting = true
export { render }

import { createSignal } from 'solid-js'
import { hydrate } from 'solid-js/web'
import { PageLayout } from './PageLayout'
import type { Route } from './PageLayout'
import type {
  /*
  // When using Client Routing https://vite-plugin-ssr.com/clientRouting
  PageContextBuiltInClientWithClientRouting as PageContextBuiltInClient
  /*/
  // When using Server Routing
  PageContextBuiltInClientWithServerRouting as PageContextBuiltInClient
  //*/
} from 'vite-plugin-ssr'
import type { PageContext } from './types'

let layoutReady = false

// Central signal to track the current active route.
const [route, setRoute] = createSignal<Route | null>(null)

function render(pageContext: PageContextBuiltInClient & PageContext) {
  const content = document.getElementById('page-view')
  const { Page, pageProps } = pageContext

  // Set the new route.
  setRoute({ Page, pageProps })

  // If haven't rendered the layout yet, do so now.
  if (!layoutReady) {
    // Render the page.
    // This is the first page rendering; the page has been rendered to HTML
    // and we now make it interactive.
    hydrate(() => <PageLayout route={() => route()} />, content!)
    layoutReady = true
  }
}

// boilerplates/boilerplate-preact/renderer/_default.page.client.jsx
import { getPage } from "vite-plugin-ssr/client";
import { PageWrapper } from "./PageWrapper";

import { render } from "preact";

hydrate();

async function hydrate() {
  // We do Server Routing, but we can also do Client Routing by using `useClientRouter()`
  // instead of `getPage()`, see https://vite-plugin-ssr.com/useClientRouter
  const pageContext = await getPage();
  const { Page, pageProps } = pageContext;
  render(
    <PageWrapper pageContext={pageContext}>
      <Page {...pageProps} />
    </PageWrapper>,
    document.getElementById("page-view")
  );
}
