// examples/solid/pages/_error.page.tsx
import { Component } from "solid-js";

export { Page };

const Page: Component<{ is404: boolean }> = (props) => {
  if (props.is404) {
    return (
      <>
        <h1>404 Page Not Found</h1>
        This page could not be found.
      </>
    );
  } else {
    return (
      <>
        <h1>500 Internal Server Error</h1>
        Something went wrong.
      </>
    );
  }
}

// boilerplates/boilerplate-preact/renderer/_error.page.jsx
export { Page };

function Page({ is404 }) {
  if (is404) {
    return (
      <>
        <h1>404 Page Not Found</h1>
        <p>This page could not be found.</p>
      </>
    );
  } else {
    return (
      <>
        <h1>500 Internal Server Error</h1>
        <p>Something went wrong.</p>
      </>
    );
  }
}
