// examples/solid-ssr-v1/renderer/_error.page.tsx
export { Page }

import type { Component } from 'solid-js'

const Page: Component<{ is404: boolean }> = ({ is404 }) => {
  if (is404) {
    return (
      <>
        <h1>404 Page Not Found</h1>
        <p>This page could not be found.</p>
      </>
    )
  } else {
    return (
      <>
        <h1>500 Internal Server Error</h1>
        <p>Something went wrong.</p>
      </>
    )
  }
}

// boilerplates/boilerplate-preact/renderer/_error.page.jsx
export { Page };

function Page({ is404 }) {
  if (is404) {
    return (
      <>
        <h1>404 Page Not Found</h1>
        <p>This page could not be found.</p>
      </>
    );
  } else {
    return (
      <>
        <h1>500 Internal Server Error</h1>
        <p>Something went wrong.</p>
      </>
    );
  }
}
