// examples/layouts-vue/pages/index/index.page.vue
<template>
  <h1>Landing Page</h1>
  <p>
    <b> This page uses the landing page layout <code>/pages/index/Layout.vue</code>. </b>
  </p>
  <p id="navigation">
    <a href="/about">About</a>
    <a href="/starship">Starship</a>
  </p>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur gravida urna id ligula volutpat dapibus. Integer
    accumsan dignissim efficitur. Sed mauris tortor, lobortis at suscipit ac, ultricies eu nunc. Curabitur luctus
    finibus tellus eget tristique. Vivamus aliquam mollis ligula at dapibus.
  </p>
  <p>
    Proin vulputate elit eget porta mollis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
    inceptos himenaeos. Etiam in nibh et lorem varius suscipit vitae vitae ligula. In blandit mattis erat. Proin congue
    cursus dui ac porta. Duis tincidunt pretium ullamcorper.
  </p>
</template>

<script>
export { default as Layout } from './Layout.vue'
</script>

// examples/layouts-react-v1/pages/index/index.page.jsx
export { Layout } from './Layout'
export { Page }

import React from 'react'

function Page() {
  return (
    <>
      <h1>Landing Page</h1>
      <p>
        <b>
          This page uses the landing page layout <code>/pages/index/Layout.jsx</code>.
        </b>
      </p>
      <p id="navigation">
        <a href="/about">About</a>
        <a href="/starship">Starship</a>
      </p>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur gravida urna id ligula volutpat dapibus.
        Integer accumsan dignissim efficitur. Sed mauris tortor, lobortis at suscipit ac, ultricies eu nunc. Curabitur
        luctus finibus tellus eget tristique. Vivamus aliquam mollis ligula at dapibus.
      </p>
      <p>
        Proin vulputate elit eget porta mollis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
        inceptos himenaeos. Etiam in nibh et lorem varius suscipit vitae vitae ligula. In blandit mattis erat. Proin
        congue cursus dui ac porta. Duis tincidunt pretium ullamcorper.
      </p>
    </>
  )
}
