// examples/react-data-fetching/pages/star-wars/@id/+Page.tsx
export default Page

import React from 'react'
import { useData } from '../../../renderer/useData'
import type { Data } from './+data'

function Page() {
  const { movie } = useData<Data>()

  return (
    <>
      <h1>{movie.title}</h1>
      Release Date: {movie.release_date}
      <br />
      Director: {movie.director}
      <br />
      Producer: {movie.producer}
    </>
  )
}

// examples/vue-full/pages/star-wars/@id/+Page.vue
<template>
  <h1>{{ data.movie.title }}</h1>
  Release Date: {{ data.movie.release_date }}
  <br />
  Director: {{ data.movie.director }}
  <br />
  Producer: {{ data.movie.producer }}
</template>

<script lang="ts" setup>
import type { Data } from './+data.shared'
import { useData } from '../../../renderer/useData'
const data = useData<Data>()
</script>
