// examples/cloudflare-workers-react-full/renderer/types.ts
export type { PageProps }

import type fetch from 'node-fetch'

type Page = (pageProps: PageProps) => React.ReactElement
type PageProps = Record<string, unknown>

// https://vike.dev/pageContext#typescript
declare global {
  namespace Vike {
    interface PageContext {
      Page: Page
      pageProps?: PageProps
      fetch?: typeof fetch
    }
  }
}

// examples/solid-ssr-v1/renderer/types.ts
import { Component } from 'solid-js'
export type PageProps = {}
type Page = Component<PageProps>

// https://vike.dev/pageContext#typescript
declare global {
  namespace Vike {
    interface PageContext {
      Page: Page
      pageProps?: PageProps
      documentProps?: {
        title?: string
        description?: string
      }
    }
  }
}
