// examples/solid-spa-v1/renderer/+onRenderClient.tsx
// https://vike.dev/onRenderClient
export { onRenderClient }

import { render } from 'solid-js/web'
import type { OnRenderClientAsync } from 'vike/types'

/**
 * A function that disposes previously rendered pages.
 *
 * If the function is not executed, each route change will
 * append a page to the DOM without clearing (disposing)
 * the previous one.
 */
let disposePreviousPage: () => void

const onRenderClient: OnRenderClientAsync = async (pageContext): ReturnType<OnRenderClientAsync> => {
  const { Page } = pageContext

  if (disposePreviousPage) {
    disposePreviousPage()
  }

  // render the page and save the dispose function of that page
  disposePreviousPage = render(() => <Page />, document.getElementById('root'))
}

// examples/react-full/renderer/+onRenderClient.tsx
// https://vike.dev/onRenderClient
export { onRenderClient }

import React from 'react'
import ReactDOM from 'react-dom/client'
import { PageShell } from './PageShell'
import { getPageTitle } from './getPageTitle'
import type { OnRenderClientAsync } from 'vike/types'

let root: ReactDOM.Root
const onRenderClient: OnRenderClientAsync = async (pageContext): ReturnType<OnRenderClientAsync> => {
  const { Page } = pageContext
  const page = (
    <PageShell pageContext={pageContext}>
      <Page />
    </PageShell>
  )
  const container = document.getElementById('react-root')!
  if (pageContext.isHydration) {
    root = ReactDOM.hydrateRoot(container, page)
  } else {
    if (!root) {
      root = ReactDOM.createRoot(container)
    }
    root.render(page)
  }
  document.title = getPageTitle(pageContext)
}
