// examples/i18n/pages/_error/+Page.jsx
export { Page }

import React from 'react'
import { usePageContext } from '../../renderer/usePageContext'

function Page() {
  const pageContext = usePageContext()
  let { is404, abortReason } = pageContext
  if (!abortReason) {
    abortReason = is404 ? 'Page not found' : 'Something went wrong'
  }
  return (
    <Center>
      <p style={{ fontSize: '1.3em' }}>{abortReason}</p>
    </Center>
  )
}

function Center({ style, ...props }) {
  return (
    <div
      style={{
        height: 'calc(100vh - 100px)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        ...style
      }}
      {...props}
    ></div>
  )
}

// packages/create-vike-core/boilerplate-vue-ts/pages/_error/+Page.vue
<template>
  <div class="center">
    <p>{{ abortReason }}</p>
  </div>
</template>

<script lang="ts" setup>
import { usePageContext } from '../../renderer/usePageContext'

const pageContext = usePageContext()
let { is404, abortReason } = pageContext.value
if (!abortReason) {
  abortReason = is404 ? 'Page not found.' : 'Something went wrong.'
}
</script>

<style>
.center {
  height: calc(100vh - 100px);
  display: flex;
  font-size: 1.3em;
  justify-content: center;
  align-items: center;
}
</style>
