// examples/solid-ssr-v1/renderer/types.ts
import { Component } from 'solid-js'
export type PageProps = {}
type Page = Component<PageProps>

// https://vike.dev/pageContext#typescript
declare global {
  namespace Vike {
    interface PageContext {
      Page: Page
      pageProps?: PageProps
      documentProps?: {
        title?: string
        description?: string
      }
    }
  }
}

// boilerplates/boilerplate-react-ts/renderer/types.ts
export type { PageProps }

// https://vike.dev/pageContext#typescript
declare global {
  namespace Vike {
    interface PageContext {
      Page: Page
      pageProps?: PageProps
      urlPathname: string
      exports: {
        documentProps?: {
          title?: string
          description?: string
        }
      }
    }
  }
}

type Page = (pageProps: PageProps) => React.ReactElement
type PageProps = Record<string, unknown>
